#GET http://localhost:8080//account/inspector/list
#Content-Type: application/json
#
#{
#  "id": "",
#  "username": "",
#  "page": 1,
#  "limit": 20,
#  "sort": "+id "
#}

#POST http://localhost:8080//account/inspector/create
#Content-Type: application/json
#
#{
#  "username": "test",
#  "password": "test",
#  "comfirm_password": "test"
#}

#POST http://localhost:8080//account/inspector/update
#Content-Type: application/json
#
#{
#  "id": 1,
#  "password": "test",
#  "comfirm_password": "test"
#}

#POST http://localhost:8080//account/inspector/delete
#Content-Type: application/json
#
#{
#  "id": 2
#}

POST http://localhost:8080//account/inspector/reset-openid
Content-Type: application/json

{
  "id": 1
}